languagedirection: rtl
languageName: ":fa:"
languageAltTitle: فارسی
title: امیر
weight: 2
profileMode:
  enabled: true
  title: امیرمحمد حسینی نسب
  imageUrl: "https://avatars.githubusercontent.com/u/19665344?v=4"
  imageTitle: عکس امیرمحمد حسینی نسب
  imageWidth: 250
  imageHeight: 250
  subtitle: فعلا هیچی ...
