theme = "apollo"
base_url = "https://amirhn.com/"
title = "itsamirhn"
description = "Personal website of Amir"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[extra]
toc = false
use_cdn = true
theme = "auto"              # light, dark, auto, toggle
fancy_code = true
repo_url = "https://github.com/itsamirhn/itsamirhn.github.io"

menu = [
    { name = "/about", url = "/about", weight = 1 },
    { name = "/now", url = "/now", weight = 2 }
]

socials = [
    { name = "github", url = "https://github.com/itsamirhn/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/itsamirhn/", icon = "linkedin" },
    { name = "telegram", url = "https://t.me/itsamirhn", icon = "telegram" },
    { name = "email", url = "mailto:awmirhn+website@gmail.com", icon = "email" },
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "amirhn"
host = "goatcounter.com"